import type { Metadata } from "next";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <div className="dashboard flex flex-row bg-gradient-to-br from-zinc-900 via-violet-900 to-rose-900">
        <Navbar />
        {children}
    </div>
  );
}
